### ISSUE TITLE
ConfigError: Missing region in config

### ISSUE THREAD

**Issue by robinheghan** [KyleBanks/lambda-uploader#1]
I get this when following the example in the readme.

ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/event_listeners.js:81:45)
    at Request.callListeners (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/config.js:267:7)
    at /Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/config.js:283:9
    at SharedIniFileCredentials.get (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/config.js:277:24)
    at Config.getCredentials (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/config.js:297:9)
    at Request.VALIDATE_CREDENTIALS (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/event_listeners.js:70:26)
    at Request.callListeners (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/skinney/Workspace/masters-of-cthulhu/node_modules/aws-sdk/lib/request.js:373:15)

**Comment by robinheghan** [comment]
Just let me know if you need more info @KyleBanks

**Comment by KyleBanks** [comment]
@Skinney I just pushed version 1.0.3 which should fix your issue
